default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  reconnect: true

# this is a stupid fallback just used for precompile
<% uri=URI.parse(ENV["DATABASE_URI"] || "postgres://dev:1234@localhost/rfeeder_development?pool=5" )%>

development:
  <<: *default
  database: rfeeder
  username: <%= uri.user %>
  password: <%= uri.password %>
  host: <%= uri.host %>

production:
  <<: *default
  database: rfeeder
  username: <%= uri.user %>
  password: <%= uri.password %>
  host: <%= uri.host %>

test:
  adapter: postgresql
  encoding: unicode
  database: rfeeder_test
  pool: 5
  username: rfeeder
  password:
